#!/bin/sh

# Cleanup previous builds and simulation files
rm -rf obj_dir
rm -f sigdelay.vcd

# Run Verilator to translate Verilog files into C++, specify sigdelay as the top module
verilator -Wall --cc --trace sigdelay.sv ram.sv --exe sigdelay_tb.cpp --top-module sigdelay

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# Run executable simulation file
./obj_dir/Vsigdelay
